[package]
name = "rush"
version = "0.1.0"
authors = ["Michal Swietek <michal.swietek@cardinals.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.9"
tokio = { version = "1", features = ["rt"] }
mini-redis = "0.4"
